version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
    # Max 5 open pull requests
    open-pull-requests-limit: 20

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
  # npm files stored in the root directory
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "monthly"
    # Max 5 open pull requests
    open-pull-requests-limit: 20
    # Default: Always increase the version requirement to match the new version
    versioning-strategy: increase
