include:
  - project: "asm/gitlab-ci-helpers"
    file: "/gitlab-ci-helpers.yml"

variables:
  KUBE_PROD_DOMAIN: docs.uninett.no
  KUBE_TEST_ID: docs
  HTTP_PORT: "80" # The port number of the web server.
  REPLICAS: "1"

stages:
  - build
  - test
  - review
  - production

eslint:
  stage: test
  image: node:14
  script:
    - npm ci
    - git ls-files '*.js' '**/*.js' | xargs ./node_modules/.bin/eslint

build:
  extends: .docker-build
  stage: build
  only:
    - branches

imagescan:
  extends: .imagescan
  stage: test
  only:
    - branches

production:
  extends: .production
  stage: production
  variables:
    REPLICAS: "2"
  script:
    - deploy deployment.yaml
  when: on_success

review:
  extends: .review
  stage: review
  script:
    - deploy deployment.yaml

stop_review:
  extends: .stop_review
  stage: review
