name: Test deployment to GitHub Pages

on:
  pull_request:
    branches:
      - master

jobs:
  test-deploy:
    name: Test deployment to GitHub Pages
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: docs
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Setup Node LTS
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      # Install modules from the package lockfile instead of package.json
      - name: Test build
        run: |
          npm ci
          npm run build